---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: ""
  namespace: argocd
spec:
  destination:
    namespace: ""
    server: https://kubernetes.default.svc
  project: previews
  source:
    helm:
      values: |
        image:
          tag: "latest"
        ingress:
          host: ".192.168.49.2.nip.io"
      version: v3
    path: helm
    repoURL: https://github.com/noimo-analytics/helm-app-1.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
